//
// Created by Roman on 4/2/2024.
//

#ifndef __GROM_ANDROIDKEYCODES_H
#define __GROM_ANDROIDKEYCODES_H

#include <android/keycodes.h>

#define NS_KEY_ENTER AKEYCODE_ENTER
#define NS_KEY_SPACE AKEYCODE_SPACE
#define NS_KEY_TAB AKEYCODE_TAB
#define NS_KEY_DOWN AKEYCODE_DPAD_DOWN
#define NS_KEY_RIGHT AKEYCODE_DPAD_RIGHT
#define NS_KEY_UP AKEYCODE_DPAD_UP
#define NS_KEY_LEFT AKEYCODE_DPAD_LEFT
#define NS_KEY_ESCAPE AKEYCODE_BACK
#define NS_KEY_BACKSPACE AKEYCODE_DEL
#define NS_KEY_LEFT_CONTROL AKEYCODE_CTRL_LEFT
#define NS_KEY_F2 AKEYCODE_F2
#define NS_KEY_F1 AKEYCODE_F1
#define NS_KEY_F3 AKEYCODE_F3
#define NS_KEY_F9 AKEYCODE_F9
#define NS_KEY_KP_PLUS AKEYCODE_PLUS
#define NS_KEY_KP_MINUS AKEYCODE_MINUS
#define NS_KEY_DELETE AKEYCODE_FORWARD_DEL
#define NS_KEY_PAGE_UP AKEYCODE_PAGE_UP
#define NS_KEY_PAGE_DOWN AKEYCODE_PAGE_DOWN
#define NS_KEY_END AKEYCODE_MOVE_END
#define NS_KEY_LEFT_ALT AKEYCODE_ALT_LEFT
#define NS_KEY_TILDE AKEYCODE_GRAVE
#define NS_KEY_Z AKEYCODE_Z
#define NS_KEY_Y AKEYCODE_Y

#define KEYBOARD_MAX_KEYS (AKEYCODE_PROFILE_SWITCH+1)

#endif //__GROM_ANDROIDKEYCODES_H
