//
// Created by Roman on 3/26/2024.
//

#ifndef _GROM_PLATFORM_DESKTOPKEYCODES_H
#define _GROM_PLATFORM_DESKTOPKEYCODES_H

#include <GLFW/glfw3.h>

#define NS_KEY_ENTER GLFW_KEY_ENTER
#define NS_KEY_SPACE GLFW_KEY_SPACE
#define NS_KEY_TAB GLFW_KEY_TAB
#define NS_KEY_DOWN GLFW_KEY_DOWN
#define NS_KEY_RIGHT GLFW_KEY_RIGHT
#define NS_KEY_UP GLFW_KEY_UP
#define NS_KEY_LEFT GLFW_KEY_LEFT
#define NS_KEY_ESCAPE GLFW_KEY_ESCAPE
#define NS_KEY_BACKSPACE GLFW_KEY_BACKSPACE
#define NS_KEY_0 GLFW_KEY_0
#define NS_KEY_1 GLFW_KEY_1
#define NS_KEY_2 GLFW_KEY_2
#define NS_KEY_3 GLFW_KEY_3
#define NS_KEY_4 GLFW_KEY_4
#define NS_KEY_5 GLFW_KEY_5
#define NS_KEY_6 GLFW_KEY_6
#define NS_KEY_7 GLFW_KEY_7
#define NS_KEY_8 GLFW_KEY_8
#define NS_KEY_9 GLFW_KEY_9
#define NS_KEY_F1 GLFW_KEY_F1
#define NS_KEY_F2 GLFW_KEY_F2
#define NS_KEY_F3 GLFW_KEY_F3
#define NS_KEY_F9 GLFW_KEY_F9
#define NS_KEY_Z GLFW_KEY_Z
#define NS_KEY_Y GLFW_KEY_Y
#define NS_KEY_N GLFW_KEY_N
#define NS_KEY_S GLFW_KEY_S
#define NS_KEY_R GLFW_KEY_R
#define NS_KEY_Q GLFW_KEY_Q
#define NS_KEY_A GLFW_KEY_A
#define NS_KEY_LEFT_CONTROL GLFW_KEY_LEFT_CONTROL
#define NS_KEY_RIGHT_CONTROL GLFW_KEY_RIGHT_CONTROL
#define NS_KEY_KP_PLUS GLFW_KEY_KP_ADD
#define NS_KEY_KP_MINUS GLFW_KEY_KP_SUBTRACT
#define NS_KEY_DELETE GLFW_KEY_DELETE
#define NS_KEY_PAGE_UP GLFW_KEY_PAGE_UP
#define NS_KEY_PAGE_DOWN GLFW_KEY_PAGE_DOWN
#define NS_KEY_END GLFW_KEY_END
#define NS_KEY_LEFT_ALT GLFW_KEY_LEFT_ALT
#define NS_KEY_TILDE GLFW_KEY_GRAVE_ACCENT
#define NS_KEY_LSHIFT GLFW_KEY_LEFT_SHIFT

#define KEYBOARD_MAX_KEYS (GLFW_KEY_LAST+1)

#endif //_GROM_PLATFORM_DESKTOPKEYCODES_H
